// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbShop2.Models;

#nullable disable

namespace WebbShop2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260102083204_AddedLeverantor")]
    partial class AddedLeverantor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProduktStorlek", b =>
                {
                    b.Property<int>("ProdukterId")
                        .HasColumnType("int");

                    b.Property<int>("StorlekarId")
                        .HasColumnType("int");

                    b.HasKey("ProdukterId", "StorlekarId");

                    b.HasIndex("StorlekarId");

                    b.ToTable("ProduktStorlek");
                });

            modelBuilder.Entity("WebbShop2.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorier");
                });

            modelBuilder.Entity("WebbShop2.Models.Leverantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KontaktInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leverantorer");
                });

            modelBuilder.Entity("WebbShop2.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnheterILager")
                        .HasColumnType("int");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int?>("LeverantorId")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("LeverantorId");

                    b.ToTable("Produkter");
                });

            modelBuilder.Entity("WebbShop2.Models.Storlek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storlekar");
                });

            modelBuilder.Entity("ProduktStorlek", b =>
                {
                    b.HasOne("WebbShop2.Models.Produkt", null)
                        .WithMany()
                        .HasForeignKey("ProdukterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbShop2.Models.Storlek", null)
                        .WithMany()
                        .HasForeignKey("StorlekarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebbShop2.Models.Produkt", b =>
                {
                    b.HasOne("WebbShop2.Models.Kategori", "Kategori")
                        .WithMany("Produkter")
                        .HasForeignKey("KategoriId");

                    b.HasOne("WebbShop2.Models.Leverantor", "Leverantor")
                        .WithMany("Produkter")
                        .HasForeignKey("LeverantorId");

                    b.Navigation("Kategori");

                    b.Navigation("Leverantor");
                });

            modelBuilder.Entity("WebbShop2.Models.Kategori", b =>
                {
                    b.Navigation("Produkter");
                });

            modelBuilder.Entity("WebbShop2.Models.Leverantor", b =>
                {
                    b.Navigation("Produkter");
                });
#pragma warning restore 612, 618
        }
    }
}
