// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbShop2.Models;

#nullable disable

namespace WebbShop2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260122105531_adf")]
    partial class adf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebbShop2.Models.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GatuAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Postnummer")
                        .HasColumnType("int");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresser");
                });

            modelBuilder.Entity("WebbShop2.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorier");
                });

            modelBuilder.Entity("WebbShop2.Models.Kund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdressId")
                        .HasColumnType("int");

                    b.Property<string>("Anvandarnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Losenord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdressId");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("WebbShop2.Models.Leverantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KontaktInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leverantorer");
                });

            modelBuilder.Entity("WebbShop2.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Erbjudande")
                        .HasColumnType("bit");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int?>("LeverantorId")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("LeverantorId");

                    b.ToTable("Produkter");
                });

            modelBuilder.Entity("WebbShop2.Models.ProduktStorlek", b =>
                {
                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.Property<int>("StorlekId")
                        .HasColumnType("int");

                    b.Property<int>("EnheterIlager")
                        .HasColumnType("int");

                    b.HasKey("ProduktId", "StorlekId");

                    b.HasIndex("StorlekId");

                    b.ToTable("ProduktStorlekar");
                });

            modelBuilder.Entity("WebbShop2.Models.Storlek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storlekar");
                });

            modelBuilder.Entity("WebbShop2.Models.Varukorg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int?>("KundId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.Property<int>("StorlekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KundId");

                    b.HasIndex("ProduktId");

                    b.HasIndex("StorlekId");

                    b.ToTable("Varukorgar");
                });

            modelBuilder.Entity("WebbShop2.Models.Kund", b =>
                {
                    b.HasOne("WebbShop2.Models.Adress", "Adress")
                        .WithMany("Kunder")
                        .HasForeignKey("AdressId");

                    b.Navigation("Adress");
                });

            modelBuilder.Entity("WebbShop2.Models.Produkt", b =>
                {
                    b.HasOne("WebbShop2.Models.Kategori", "Kategori")
                        .WithMany("Produkter")
                        .HasForeignKey("KategoriId");

                    b.HasOne("WebbShop2.Models.Leverantor", "Leverantor")
                        .WithMany("Produkter")
                        .HasForeignKey("LeverantorId");

                    b.Navigation("Kategori");

                    b.Navigation("Leverantor");
                });

            modelBuilder.Entity("WebbShop2.Models.ProduktStorlek", b =>
                {
                    b.HasOne("WebbShop2.Models.Produkt", "Produkt")
                        .WithMany("ProduktStorlekar")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbShop2.Models.Storlek", "Storlek")
                        .WithMany("ProduktStorlekar")
                        .HasForeignKey("StorlekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");

                    b.Navigation("Storlek");
                });

            modelBuilder.Entity("WebbShop2.Models.Varukorg", b =>
                {
                    b.HasOne("WebbShop2.Models.Kund", "Kund")
                        .WithMany("Varukorgar")
                        .HasForeignKey("KundId");

                    b.HasOne("WebbShop2.Models.Produkt", "Produkt")
                        .WithMany("Varukorgar")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbShop2.Models.Storlek", "Storlek")
                        .WithMany("Varukorgar")
                        .HasForeignKey("StorlekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("Produkt");

                    b.Navigation("Storlek");
                });

            modelBuilder.Entity("WebbShop2.Models.Adress", b =>
                {
                    b.Navigation("Kunder");
                });

            modelBuilder.Entity("WebbShop2.Models.Kategori", b =>
                {
                    b.Navigation("Produkter");
                });

            modelBuilder.Entity("WebbShop2.Models.Kund", b =>
                {
                    b.Navigation("Varukorgar");
                });

            modelBuilder.Entity("WebbShop2.Models.Leverantor", b =>
                {
                    b.Navigation("Produkter");
                });

            modelBuilder.Entity("WebbShop2.Models.Produkt", b =>
                {
                    b.Navigation("ProduktStorlekar");

                    b.Navigation("Varukorgar");
                });

            modelBuilder.Entity("WebbShop2.Models.Storlek", b =>
                {
                    b.Navigation("ProduktStorlekar");

                    b.Navigation("Varukorgar");
                });
#pragma warning restore 612, 618
        }
    }
}
